spring:
  application:
    name: secret-stash
  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_schema: "\"secret-notes\""
      open-in-view: false
    datasource:
      hikari:
        driver-class-name: org.postgresql.Driver